import { test, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';

test('galeria filtra, amplia fotos e carrega vídeos somente sob demanda', async ({ page }) => {
  const videoRequests: string[] = [];
  page.on('request', request => { if (request.url().endsWith('.mp4')) videoRequests.push(request.url()); });
  await page.goto('/');
  const gallery = page.locator('#galeria');
  await gallery.scrollIntoViewIfNeeded();
  await expect(gallery.locator('.gallery-card')).toHaveCount(6);
  expect(videoRequests).toEqual([]);
  await gallery.getByRole('button', { name: 'Ver mais registros' }).click();
  await expect(gallery.locator('.gallery-card')).toHaveCount(8);
  await gallery.getByRole('button', { name: 'Fotos', exact: true }).click();
  await expect(gallery.locator('.gallery-card')).toHaveCount(3);
  const photoButton = gallery.getByRole('button', { name: 'Ampliar: Atenção em cada atendimento' });
  await photoButton.click();
  const dialog = page.getByRole('dialog');
  await expect(dialog).toBeVisible();
  await expect(dialog.locator('.viewer-photo')).toBeVisible();
  const audit = await new AxeBuilder({ page }).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();
  expect(audit.violations).toEqual([]);
  await page.keyboard.press('Escape');
  await expect(dialog).not.toBeVisible();
  await expect(photoButton).toBeFocused();
  await gallery.getByRole('button', { name: 'Vídeos', exact: true }).click();
  await expect(gallery.locator('.gallery-card')).toHaveCount(5);
  await gallery.getByRole('button', { name: 'Assistir: Movimento no esporte' }).click();
  const video = dialog.locator('video');
  await expect(video).toHaveAttribute('preload', 'none');
  await expect(video).not.toHaveAttribute('autoplay');
  expect(videoRequests).toEqual([]);
  await video.evaluate(async (element: HTMLVideoElement) => { element.muted = true; await element.play(); });
  await expect.poll(() => video.evaluate((element: HTMLVideoElement) => element.currentTime)).toBeGreaterThan(0);
  expect(videoRequests.length).toBeGreaterThan(0);
  await dialog.getByRole('button', { name: 'Fechar visualização' }).click();
  await expect(page.locator('video')).toHaveCount(0);
  await gallery.getByRole('button', { name: 'Assistir ao vídeo de cuidado individualizado' }).click();
  await expect(dialog.locator('source')).toHaveAttribute('src', 'media/videos/cuidado-individualizado.mp4');
  await expect(dialog).not.toContainText(/Lázaro|Lazaro|tetrapl/i);
  await expect(gallery).not.toContainText(/Lázaro|Lazaro|tetrapl/i);
  await page.keyboard.press('Escape');
  await expect(dialog).not.toBeVisible();
});
